[tool:pytest]
DJANGO_SETTINGS_MODULE = board_project.settings
python_files = tests.py test_*.py *_tests.py
testpaths = ads, users

# Ключевая строка — активация pytest-django!
addopts = --ds=board_project.settings --tb=short